### ISSUE TITLE
Access to the 'brotli' crates.io name

### ISSUE THREAD

**Issue by frewsxcv** [ende76/brotli-rs#18]
https://crates.io/crates/brotli

Servo has ownership of this name right now, but we can grant you access if you want. You just need to log in to (and by doing so 'creating') your crates.io account.

**Comment by ende76** [comment]
@frewsxcv I guess, I'm a bit apprehensive about a cargo release. On the other hand, by now the library has probably been as thoroughly vetted as it is going to be.
I'll leave the issue open, and let you know when I make the move.

**Comment by danielrh** [comment]
@frewsxcv This library is really well organized and easy to read; however, the dropbox direct port of the google brotli C code to pure rust ( http://github.com/dropbox/rust-brotli.git ) may make more sense for the standard crates.io since I just benchmarked its performance to be ~comparable (within ~30%) with the purely optimized C version.

**Comment by SimonSapin** [comment]
> I guess, I'm a bit apprehensive about a cargo release.

Given this, I’ve given @danielrh access to https://crates.io/crates/brotli. So assuming it gets used for dropbox/rust-brotli, if/when this crate is published on crates.io it’ll need another package name to disambiguate. Note that the package name (for crates.io and `[dependencies]`) doesn’t have to be the same as the crate name (for `extern crate`).

**Comment by ende76** [comment]
Seems like a good conclusion to this issue.
