### ISSUE TITLE
brotli-rs fails to decompress item compressed with -q 4 -w 16

### ISSUE THREAD

**Issue by danielrh** [ende76/brotli-rs#19]
I tried this on the bro binary from google and it fails to decompress with brotli-rs when compressed using -q 4 -w 16

https://www.dropbox.com/s/il9uhagaaawxl6i/bro?dl=0

https://www.dropbox.com/s/2lb4dzpjczbv8ll/bro.br?dl=0

but this is true for almost every binary I checked...
in fact I just wrote a checker script that simply, in a loop, compresses with bro -q X -w Y
where x = {1..11} and y = {16..22}
That's how I found this glitch.

**Comment by danielrh** [comment]
Probably not helpful but here's the stack trace

351153
thread '<main>' panicked at 'index out of bounds: the len is 16 but the index is 31', ../src/libcollections/vec.rs:1134
stack backtrace:
   1:        0x10ac55168 - sys::backtrace::tracing::imp::write::ha0f40157033dab87T8t
   2:        0x10ac568e5 - panicking::default_handler::_<closure>::closure.42228
   3:        0x10ac56444 - panicking::default_handler::hfa48369cd11de99dKcy
   4:        0x10ac4e844 - sys_common::unwind::begin_unwind_inner::h1122abee381015baUbt
   5:        0x10ac4eace - sys_common::unwind::begin_unwind_fmt::h3636a0d12a6c9e2f0at
   6:        0x10ac54767 - rust_begin_unwind
   7:        0x10ac76a90 - panicking::panic_fmt::h596d44ac9aaebe47nYL
   8:        0x10ac76c10 - panicking::panic_bounds_check::hb399db976cf4f929tXL
   9:        0x10ac39e6f - Decompressor<R>::decompress::h10570345981971389827
  10:        0x10ac2d152 - main::h60ef4bbe838695fcmaa
  11:        0x10ac560c2 - sys_common::unwind::try::try_fn::h6542981591240630136
  12:        0x10ac54708 - __rust_try
  13:        0x10ac55f65 - rt::lang_start::h83533f65c37de1a9Q4x

**Comment by ende76** [comment]
@danielrh Thanks a lot for reporting this.
First thoughts, mostly as notes to myself:

- The stack trace is useful insofar as I can't think of many Vecs in the code that have a length of 16… The context map for distances might be a good candidate to look into (See 7.3. Encoding of the context map),
- It is a bit surprising that this bug has gone unnoticed for so long. Possibly because it's mostly used for text compression. 'Binary' would probably be significant for the choice of context mode (see 7.1. Context modes and context ID lookup for literals),
- Hopefully, this bug can be replicated with very small binary files, as manual inspection might be necessary,
- Might have to break out gdb (also see http://rr-project.org/ )
